### ISSUE TITLE
Failed to reinstall Debian 9

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-package#28]
Here is test case:
1. dpkg -i gluu-server-3.1.5_1-5~Db9stretch_amd64.deb
2. gluu-serverd-3.1.5 start
3. dpkg -P gluu-server-3.1.5
4. dpkg -i gluu-server-3.1.5_1-5~Db9stretch_amd64.deb
5. gluu-serverd-3.1.5 start
6. gluu-serverd-3.1.5 login

If after step 2 we run `gluu-serverd-3.1.5 stop` the flow is working fine. I think before uninstalling package we don't store gluu-server properly.

**Comment by adrian-gluu** [comment]
tested latest build and this issue is sorted:
root@debian9:~# dpkg -i gluu-server-3.1.5_1-7~Db9stretch_amd64.deb 
Selecting previously unselected package gluu-server-3.1.5.
(Reading database ... 100124 files and directories currently installed.)
Preparing to unpack gluu-server-3.1.5_1-7~Db9stretch_amd64.deb ...
Unpacking gluu-server-3.1.5 (1-7~Db9stretch) ...
Setting up gluu-server-3.1.5 (1-7~Db9stretch) ...
root@debian9:~# gluu-serverd-3.1.5 start
root@debian9:~# dpkg -P gluu-server-3.1.5
(Reading database ... 138137 files and directories currently installed.)
Removing gluu-server-3.1.5 (1-7~Db9stretch) ...
Checking to make sure Gluu Server is down...
Your changes will be saved into /opt/gluu-server-3.1.5.saved
Purging configuration files for gluu-server-3.1.5 (1-7~Db9stretch) ...
Your changes will be saved into /opt/gluu-server-3.1.5.saved
root@debian9:~# dpkg -i gluu-server-3.1.5_1-7~Db9stretch_amd64.deb 
Selecting previously unselected package gluu-server-3.1.5.
(Reading database ... 100124 files and directories currently installed.)
Preparing to unpack gluu-server-3.1.5_1-7~Db9stretch_amd64.deb ...
Unpacking gluu-server-3.1.5 (1-7~Db9stretch) ...
Setting up gluu-server-3.1.5 (1-7~Db9stretch) ...
root@debian9:~# gluu-serverd-3.1.5 start
root@debian9:~# gluu-serverd-3.1.5 login
Linux debian9 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have mail.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@debian9:~#

**Comment by yurem** [comment]
Confirmed. Can you check if there is no same issue in other systemd based dist?
